// Tool registry with unique IDs and metadata
export interface ToolDefinition {
  id: string
  name: string
  category: string
  description: string
  icon?: string
  isPremium?: boolean
  solution?: string
  href?: string
}

export const TOOL_REGISTRY: Record<string, ToolDefinition> = {
  "domain-name-genie": {
    id: "domain-name-genie",
    name: "Domain Name Genie",
    category: "branding",
    description: "Find your perfect domain with AI-powered suggestions based on your business description",
    icon: "Globe",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/domain-name-generator",
  },
  "tagline-creator": {
    id: "tagline-creator",
    name: "Tagline & Value-Prop Creator",
    category: "branding",
    description: "Crafts a punchy tagline and 1-sentence UVP based on user inputs",
    icon: "Type",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/tagline-value-prop-creator",
  },
  "hero-copy-generator": {
    id: "hero-copy-generator",
    name: "Landing-Page Hero Copy Generator",
    category: "content",
    description: "Generates headline, sub-headline, and CTA variations for conversion",
    icon: "LayoutTemplate",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/landing-pageherocopygenerator",
  },
  "social-media-suggester": {
    id: "social-media-suggester",
    name: "Social-Media Caption & Hashtag Suggester",
    category: "marketing",
    description: "Creates platform-tailored captions plus trending hashtags",
    icon: "Share2",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/social-media-suggester",
  },
  "blog-outline-builder": {
    id: "blog-outline-builder",
    name: "Blog-Post Topic & Outline Builder",
    category: "content",
    description: "Spins up a SEO-optimized blog structure with headings and key points",
    icon: "Rss",
    isPremium: false,
    solution: "Intelligence",
    href: "/tools/blog-generator",
  },
  "email-subject-generator": {
    id: "email-subject-generator",
    name: "Email Subject-Line & Preview-Text Generator",
    category: "marketing",
    description: "Produces subject lines and preheader options to maximize opens",
    icon: "Mail",
    isPremium: false,
    solution: "Intelligence",
    href: "/tools/email-subject-line",
  },
  "ai-business-plan-generator": {
    id: "ai-business-plan-generator",
    name: "AI Business Plan Generator",
    category: "automation",
    description: "Effortless Business Planning with AI",
    icon: "Bot",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/ai-business-plan-generator",
  },
  "powerbi-generator": {
    id: "powerbi-generator",
    name: "Power BI Measure & Viz Snippet Generator",
    category: "analytics",
    description: "Outputs DAX measures and a JSON snippet for a chart from KPI description",
    icon: "BarChart2",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/power-bi-measure",
  },
  "meeting-extractor": {
    id: "meeting-extractor",
    name: "Meeting-Summary & Action-Item Extractor",
    category: "productivity",
    description: "Get bullet-point summary + assigned tasks from transcript or notes",
    icon: "ClipboardList",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/meeting-summary-extractor",
  },
  "data-cleanse-helper": {
    id: "data-cleanse-helper",
    name: "Data-Cleanse & Schema-Map Helper",
    category: "analytics",
    description: "Infers column types, flags anomalies, and proposes a star-schema from CSV",
    icon: "Filter",
    isPremium: false,
    solution: "Intelligence",
    href: "/tools/data-cleanse",
  },
  "seo-analyzer": {
    id: "seo-analyzer",
    name: "SEO-Keyword & Content-Gap Analyzer",
    category: "marketing",
    description: "Delivers untapped keyword ideas and content gaps versus competitors",
    icon: "FileSearch",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/seo-keyword-content-gapanalyzer",
  },
  "proposal-generator": {
    id: "proposal-generator",
    name: "Proposal-Draft Generator",
    category: "business",
    description: "Get a formatted first-draft proposal from prospect details & service package",
    icon: "Briefcase",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/proposal-draft-generator",
  },
  "follow-up-email-sequencer": {
    id: "follow-up-email-sequencer",
    name: "Follow-Up Email Sequencer",
    category: "marketing",
    description: "Create automated email sequences to nurture leads and close deals effectively",
    icon: "Send",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/follow-up-email-sequencer",
  },
  "job-description-generator": {
    id: "job-description-generator",
    name: "Job Description Generator",
    category: "business",
    description: "Generate comprehensive job descriptions with requirements and responsibilities",
    icon: "UserPlus",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/job-description-generator",
  },
  "customer-persona-generator": {
    id: "customer-persona-generator",
    name: "Customer Persona & ICP Generator",
    category: "marketing",
    description: "Create detailed customer personas and ideal customer profiles for targeted marketing",
    icon: "Users",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/customer-persona-generator",
  },
  "logo-color-picker": {
    id: "logo-color-picker",
    name: "Logo Color Palette Picker",
    category: "branding",
    description: "Generate harmonious color palettes for your brand and logo design",
    icon: "Palette",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/logo-color-palette-picker",
  },
  "pricing-calculator": {
    id: "pricing-calculator",
    name: "Pricing Calculator",
    category: "business",
    description: "Calculate optimal pricing strategies based on costs, market analysis, and profit margins",
    icon: "Calculator",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/pricing-generator",
  },
  "invoice-template-builder": {
    id: "invoice-template-builder",
    name: "Invoice Template Builder",
    category: "business",
    description: "Create professional invoice templates with custom branding and automated calculations",
    icon: "Receipt",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/invoice-template-builder",
  },
  "sales-script-generator": {
    id: "sales-script-generator",
    name: "Sales Script Generator",
    category: "marketing",
    description: "Generate persuasive sales scripts for calls, emails, and presentations",
    icon: "MessageSquare",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/sales-script-generator",
  },
  "faq-builder": {
    id: "faq-builder",
    name: "FAQ Builder",
    category: "content",
    description: "Build comprehensive FAQ sections to address common customer questions",
    icon: "HelpCircle",
    isPremium: false,
    solution: "LaunchPad",
    href: "/tools/faq-builder",
  },
  "press-release-template": {
    id: "press-release-template",
    name: "Press Release Template",
    category: "marketing",
    description: "Create professional press releases for announcements and media outreach",
    icon: "Megaphone",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/press-release-template",
  },
  "project-timeline-builder": {
    id: "project-timeline-builder",
    name: "Project Timeline Builder",
    category: "productivity",
    description: "Build detailed project timelines with milestones, dependencies, and resource allocation",
    icon: "Clock",
    isPremium: false,
    solution: "GrowthSuite",
    href: "/tools/project-timeline-builder",
  },
  "domain-name-generator": {
    id: "domain-name-generator",
    name: "Domain Name Generator",
    category: "business",
    description: "AI-powered domain name suggestions",
    icon: "Globe",
    isPremium: false,
  },
  "landing-page-copy": {
    id: "landing-page-copy",
    name: "Landing Page Copy Generator",
    category: "marketing",
    description: "Generate compelling headlines and CTAs",
    icon: "LayoutTemplate",
    isPremium: false,
  },
  "business-plan-generator": {
    id: "business-plan-generator",
    name: "Business Plan Generator",
    category: "business",
    description: "AI-powered business plan creation",
    icon: "Bot",
    isPremium: true,
  },
  "whatsapp-automation": {
    id: "whatsapp-automation",
    name: "WhatsApp Automation",
    category: "automation",
    description: "WhatsApp CRM and automation setup",
    icon: "MessageSquare",
    isPremium: true,
  },
  "power-bi-consulting": {
    id: "power-bi-consulting",
    name: "Power BI Consulting",
    category: "analytics",
    description: "Business intelligence and data visualization",
    icon: "BarChart3",
    isPremium: true,
  },
}

export function getToolById(toolId: string): ToolDefinition | null {
  return TOOL_REGISTRY[toolId] || null
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter((tool) => tool.category === category)
}

export function getAllTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY)
}
