import {
  Globe,
  Type,
  LayoutTemplate,
  Share2,
  Rss,
  Mail,
  Bot,
  BarChart2,
  ClipboardList,
  Filter,
  FileSearch,
  Briefcase,
  Send,
  UserPlus,
  Users,
  Palette,
  Calculator,
  Receipt,
  MessageSquare,
  HelpCircle,
  Megaphone,
  Clock,
} from "lucide-react"

export const tools = [
  {
    id: "domain-name-genie",
    name: "Domain Name Genie",
    description: "Find your perfect domain with AI-powered suggestions based on your business description.",
    icon: Globe,
    href: "/tools/domain-name-generator",
    status: "Available",
    category: "Branding",
    solution: "LaunchPad",
    features: ["AI-powered suggestions", "Real-time availability check", "Multiple TLD options"],
    keywords: ["domain", "website", "url", "web address", "online presence", "site", "domain name", "hosting"],
    useCases: ["starting website", "new business", "rebranding", "online launch", "web presence"],
    userPersonas: ["entrepreneur", "startup founder", "small business owner", "web developer"],
    businessStages: ["idea", "launch"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "tagline-creator",
    name: "Tagline & Value-Prop Creator",
    description: "Crafts a punchy tagline and 1-sentence UVP based on user inputs.",
    icon: Type,
    href: "/tools/tagline-value-prop-creator",
    status: "Available",
    category: "Branding",
    solution: "LaunchPad",
    features: ["Punchy taglines", "Value propositions", "Brand messaging"],
    keywords: ["tagline", "value proposition", "slogan", "messaging", "brand voice", "marketing copy", "branding"],
    useCases: ["brand messaging", "marketing materials", "website copy", "brand identity", "startup branding"],
    userPersonas: ["marketer", "business owner", "brand manager", "entrepreneur"],
    businessStages: ["launch", "growth"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "hero-copy-generator",
    name: "Landing-Page Hero Copy Generator",
    description: "Generates headline, sub-headline, and CTA variations for conversion.",
    icon: LayoutTemplate,
    href: "/tools/landing-pageherocopygenerator",
    status: "Available",
    category: "Content",
    solution: "LaunchPad",
    features: ["Headlines", "Sub-headlines", "CTA variations"],
    keywords: ["landing page", "hero copy", "headlines", "conversion", "website copy", "CTA", "call to action"],
    useCases: ["website launch", "conversion optimization", "landing page creation", "marketing campaigns"],
    userPersonas: ["marketer", "web designer", "business owner", "copywriter"],
    businessStages: ["launch", "growth"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "social-media-suggester",
    name: "Social-Media Caption & Hashtag Suggester",
    description: "Creates platform-tailored captions plus trending hashtags.",
    icon: Share2,
    href: "/tools/social-media-suggester",
    status: "Available",
    category: "Marketing",
    solution: "LaunchPad",
    features: ["Platform-specific captions", "Trending hashtags", "Engagement optimization"],
    keywords: [
      "social media",
      "captions",
      "hashtags",
      "posts",
      "content",
      "engagement",
      "facebook",
      "instagram",
      "twitter",
    ],
    useCases: [
      "social media marketing",
      "content creation",
      "audience engagement",
      "brand awareness",
      "social posting",
    ],
    userPersonas: ["content creator", "social media manager", "marketer", "small business owner"],
    businessStages: ["launch", "growth", "scale"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "blog-outline-builder",
    name: "Blog-Post Topic & Outline Builder",
    description: "Spins up a SEO-optimized blog structure with headings and key points.",
    icon: Rss,
    href: "/tools/blog-generator",
    status: "Available",
    category: "Content",
    solution: "Intelligence",
    features: ["SEO optimization", "Content structure", "Topic research"],
    keywords: ["blog", "content", "SEO", "writing", "articles", "blog posts", "content marketing", "outline"],
    useCases: ["content marketing", "blog writing", "SEO content", "thought leadership", "website content"],
    userPersonas: ["content writer", "marketer", "blogger", "business owner"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "short" as const,
  },
  {
    id: "email-subject-generator",
    name: "Email Subject-Line & Preview-Text Generator",
    description: "Produces subject lines and preheader options to maximize opens.",
    icon: Mail,
    href: "/tools/email-subject-line",
    status: "Available",
    category: "Marketing",
    solution: "Intelligence",
    features: ["Subject line optimization", "Preview text", "Open rate improvement"],
    keywords: ["email", "subject lines", "newsletter", "email marketing", "open rates", "email campaigns"],
    useCases: ["email campaigns", "newsletter marketing", "lead nurturing", "customer communication"],
    userPersonas: ["email marketer", "business owner", "marketing manager"],
    businessStages: ["growth", "scale"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "ai-business-plan-generator",
    name: "AI Business Plan Generator",
    description: "Effortless Business Planning with AI",
    icon: Bot,
    href: "/tools/ai-business-plan-generator",
    status: "Available",
    category: "Automation",
    solution: "LaunchPad",
    features: [
      "AI-powered business summaries",
      "Realistic financial projections",
      "Detailed end-to-end Business strategies",
    ],
    keywords: ["business plan", "startup", "strategy", "financial projections", "business model", "planning"],
    useCases: ["startup planning", "investor pitch", "business strategy", "funding applications"],
    userPersonas: ["entrepreneur", "startup founder", "business owner"],
    businessStages: ["idea", "launch"],
    complexityLevel: "intermediate" as const,
    timeToValue: "medium" as const,
  },
  {
    id: "powerbi-generator",
    name: "Power BI Measure & Viz Snippet Generator",
    description: "Outputs DAX measures and a JSON snippet for a chart from KPI description.",
    icon: BarChart2,
    href: "/tools/power-bi-measure",
    status: "Available",
    category: "Analytics",
    solution: "GrowthSuite",
    features: ["DAX measures", "Visualization snippets", "KPI tracking"],
    keywords: ["power bi", "analytics", "data visualization", "DAX", "business intelligence", "reporting", "KPI"],
    useCases: ["business reporting", "data analysis", "dashboard creation", "performance tracking"],
    userPersonas: ["data analyst", "business analyst", "manager", "executive"],
    businessStages: ["growth", "scale"],
    complexityLevel: "advanced" as const,
    timeToValue: "medium" as const,
  },
  {
    id: "meeting-extractor",
    name: "Meeting-Summary & Action-Item Extractor",
    description: "Get bullet-point summary + assigned tasks from transcript or notes.",
    icon: ClipboardList,
    href: "/tools/meeting-summary-extractor",
    status: "Available",
    category: "Productivity",
    solution: "GrowthSuite",
    features: ["Meeting summaries", "Action items", "Task assignment"],
    keywords: ["meetings", "productivity", "summaries", "action items", "notes", "tasks", "collaboration"],
    useCases: ["meeting management", "team collaboration", "project tracking", "task management"],
    userPersonas: ["manager", "team lead", "project manager", "executive"],
    businessStages: ["growth", "scale"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "data-cleanse-helper",
    name: "Data-Cleanse & Schema-Map Helper",
    description: "Infers column types, flags anomalies, and proposes a star-schema from CSV.",
    icon: Filter,
    href: "/tools/data-cleanse",
    status: "Available",
    category: "Analytics",
    solution: "Intelligence",
    features: ["Data cleaning", "Schema mapping", "Anomaly detection"],
    keywords: ["data", "csv", "data cleaning", "analytics", "data processing", "schema", "database"],
    useCases: ["data preparation", "analytics setup", "data migration", "database design"],
    userPersonas: ["data analyst", "developer", "business analyst"],
    businessStages: ["growth", "scale"],
    complexityLevel: "advanced" as const,
    timeToValue: "medium" as const,
  },
  {
    id: "seo-analyzer",
    name: "SEO-Keyword & Content-Gap Analyzer",
    description: "Delivers untapped keyword ideas and content gaps versus competitors.",
    icon: FileSearch,
    href: "/tools/seo-keyword-content-gapanalyzer",
    status: "Available",
    category: "Marketing",
    solution: "GrowthSuite",
    features: ["Keyword research", "Content gaps", "Competitor analysis"],
    keywords: ["SEO", "keywords", "search engine", "google", "content gap", "competitor analysis", "ranking"],
    useCases: ["SEO optimization", "content strategy", "competitor research", "website ranking"],
    userPersonas: ["SEO specialist", "marketer", "content manager"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "medium" as const,
  },
  {
    id: "proposal-generator",
    name: "Proposal-Draft Generator",
    description: "Get a formatted first-draft proposal from prospect details & service package.",
    icon: Briefcase,
    href: "/tools/proposal-draft-generator",
    status: "Available",
    category: "Business",
    solution: "GrowthSuite",
    features: ["Proposal drafts", "Service packages", "Client customization"],
    keywords: ["proposal", "client", "services", "business development", "sales", "contracts", "quotes"],
    useCases: ["client proposals", "service quotes", "project bids", "business development"],
    userPersonas: ["sales person", "business owner", "consultant", "agency owner"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "short" as const,
  },
  {
    id: "follow-up-email-sequencer",
    name: "Follow-Up Email Sequencer",
    description: "Create automated email sequences to nurture leads and close deals effectively.",
    icon: Send,
    href: "/tools/follow-up-email-sequencer",
    status: "Available",
    category: "Marketing",
    solution: "GrowthSuite",
    features: ["Email sequences", "Lead nurturing", "Automated follow-ups"],
    keywords: ["email automation", "follow up", "lead nurturing", "email sequence", "sales funnel", "drip campaign"],
    useCases: ["lead nurturing", "sales automation", "customer onboarding", "email marketing"],
    userPersonas: ["sales person", "marketer", "business owner"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "medium" as const,
  },
  {
    id: "job-description-generator",
    name: "Job Description Generator",
    description: "Generate comprehensive job descriptions with requirements and responsibilities.",
    icon: UserPlus,
    href: "/tools/job-description-generator",
    status: "Available",
    category: "Business",
    solution: "GrowthSuite",
    features: ["Role requirements", "Responsibility mapping", "Skills assessment"],
    keywords: ["hiring", "job description", "recruitment", "HR", "job posting", "talent acquisition"],
    useCases: ["hiring process", "team building", "recruitment", "job postings"],
    userPersonas: ["HR manager", "business owner", "team lead"],
    businessStages: ["launch", "growth"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "customer-persona-generator",
    name: "Customer Persona & ICP Generator",
    description: "Create detailed customer personas and ideal customer profiles for targeted marketing.",
    icon: Users,
    href: "/tools/customer-persona-generator",
    status: "Available",
    category: "Marketing",
    solution: "GrowthSuite",
    features: ["Detailed personas", "ICP mapping", "Target audience insights"],
    keywords: [
      "customer persona",
      "target audience",
      "ICP",
      "ideal customer",
      "marketing strategy",
      "customer research",
    ],
    useCases: ["marketing strategy", "product development", "sales targeting", "customer research"],
    userPersonas: ["marketer", "product manager", "business owner"],
    businessStages: ["launch", "growth"],
    complexityLevel: "intermediate" as const,
    timeToValue: "short" as const,
  },
  {
    id: "logo-color-picker",
    name: "Logo Color Palette Picker",
    description: "Generate harmonious color palettes for your brand and logo design.",
    icon: Palette,
    href: "/tools/logo-color-palette-picker",
    status: "Available",
    category: "Branding",
    solution: "LaunchPad",
    features: ["Color harmony analysis", "Brand color schemes", "Accessibility compliance"],
    keywords: ["logo", "colors", "branding", "design", "color palette", "brand identity", "visual design"],
    useCases: ["brand design", "logo creation", "visual identity", "design system"],
    userPersonas: ["designer", "business owner", "brand manager"],
    businessStages: ["idea", "launch"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "pricing-calculator",
    name: "Pricing Calculator",
    description: "Calculate optimal pricing strategies based on costs, market analysis, and profit margins.",
    icon: Calculator,
    href: "/tools/pricing-generator",
    status: "Available",
    category: "Business",
    solution: "LaunchPad",
    features: ["Cost analysis", "Profit margin optimization", "Competitive pricing"],
    keywords: ["pricing", "cost analysis", "profit margins", "pricing strategy", "business model", "revenue"],
    useCases: ["product pricing", "service pricing", "business planning", "profit optimization"],
    userPersonas: ["business owner", "product manager", "entrepreneur"],
    businessStages: ["launch", "growth"],
    complexityLevel: "intermediate" as const,
    timeToValue: "short" as const,
  },
  {
    id: "invoice-template-builder",
    name: "Invoice Template Builder",
    description: "Create professional invoice templates with custom branding and automated calculations.",
    icon: Receipt,
    href: "/tools/invoice-template-builder",
    status: "Available",
    category: "Business",
    solution: "GrowthSuite",
    features: ["Custom templates", "Automated calculations", "Brand integration"],
    keywords: ["invoice", "billing", "accounting", "templates", "business documents", "payment"],
    useCases: ["client billing", "business accounting", "invoice management", "payment processing"],
    userPersonas: ["business owner", "freelancer", "accountant"],
    businessStages: ["launch", "growth", "scale"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "sales-script-generator",
    name: "Sales Script Generator",
    description: "Generate persuasive sales scripts for calls, emails, and presentations.",
    icon: MessageSquare,
    href: "/tools/sales-script-generator",
    status: "Available",
    category: "Marketing",
    solution: "GrowthSuite",
    features: ["Persuasive scripts", "Objection handling", "Closing techniques"],
    keywords: ["sales", "scripts", "cold calling", "sales pitch", "closing", "objection handling", "sales training"],
    useCases: ["sales calls", "sales training", "lead conversion", "sales presentations"],
    userPersonas: ["sales person", "business owner", "sales manager"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "faq-builder",
    name: "FAQ Builder",
    description: "Build comprehensive FAQ sections to address common customer questions.",
    icon: HelpCircle,
    href: "/tools/faq-builder",
    status: "Available",
    category: "Content",
    solution: "LaunchPad",
    features: ["Question categorization", "Answer optimization", "Search functionality"],
    keywords: ["FAQ", "customer support", "help documentation", "questions", "support content", "customer service"],
    useCases: ["customer support", "website content", "product documentation", "user guidance"],
    userPersonas: ["customer support", "business owner", "product manager"],
    businessStages: ["launch", "growth"],
    complexityLevel: "beginner" as const,
    timeToValue: "immediate" as const,
  },
  {
    id: "press-release-template",
    name: "Press Release Template",
    description: "Create professional press releases for announcements and media outreach.",
    icon: Megaphone,
    href: "/tools/press-release-template",
    status: "Available",
    category: "Marketing",
    solution: "GrowthSuite",
    features: ["Media-ready format", "SEO optimization", "Distribution guidelines"],
    keywords: ["press release", "PR", "media", "announcements", "publicity", "news", "media outreach"],
    useCases: ["product launches", "company announcements", "media relations", "publicity"],
    userPersonas: ["PR manager", "marketer", "business owner"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "short" as const,
  },
  {
    id: "project-timeline-builder",
    name: "Project Timeline Builder",
    description: "Build detailed project timelines with milestones, dependencies, and resource allocation.",
    icon: Clock,
    href: "/tools/project-timeline-builder",
    status: "Available",
    category: "Productivity",
    solution: "GrowthSuite",
    features: ["Milestone tracking", "Dependency mapping", "Resource planning"],
    keywords: ["project management", "timeline", "milestones", "project planning", "scheduling", "resource management"],
    useCases: ["project planning", "team coordination", "deadline management", "resource allocation"],
    userPersonas: ["project manager", "team lead", "business owner"],
    businessStages: ["growth", "scale"],
    complexityLevel: "intermediate" as const,
    timeToValue: "medium" as const,
  },
]

export type Tool = (typeof tools)[0]
